/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function rollWalkerTable(quantity: number, indexWeights: Float32Array): string
export declare function simulateChances(rolls: number, chance: number): number
